# EcoPlots Python Library
# Use case 2 - Plant occurrence - vegetation height

In [51]:
%pip install terndata.ecoplots

Requirement already satisfied: terndata.ecoplots in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (0.0.4b0)
Requirement already satisfied: typing-extensions in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from terndata.ecoplots) (4.15.0)
Requirement already satisfied: numpy in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from terndata.ecoplots) (2.3.5)
Requirement already satisfied: pandas in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from terndata.ecoplots) (2.3.3)
Requirement already satisfied: geopandas in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from terndata.ecoplots) (1.1.1)
Requirement already satisfied: requests in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from terndata.ecoplots) (2.32.5)
Requirement already satisfied: aiohttp<4.0.0,>=3.11.12 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from terndata.ecoplots) (3.13.2)
Requirement already satisfied: python-dateutil in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from terndata.ecoplots) (2.9.0.post0)
Requirement already satisfied: pytz in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from terndata.ecoplots) (2025.2)
Requirement already satisfied: rapidfuzz<4.0.0,>=3.13.0 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from terndata.ecoplots) (3.14.3)
Requirement already satisfied: orjson<4.0.0,>=3.10.15 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from terndata.ecoplots) (3.11.4)
Requirement already satisfied: diskcache<6.0.0,>=5.6.3 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from terndata.ecoplots) (5.6.3)
Requirement already satisfied: ijson<4.0.0,>=3.4.0 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from terndata.ecoplots) (3.4.0.post0)
Requirement already satisfied: defusedxml<1.0.0,>=0.7.1 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from terndata.ecoplots) (0.7.1)
Requirement already satisfied: shapely<3.0.0,>=2.0.0 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from terndata.ecoplots) (2.1.2)
Requirement already satisfied: ipyleaflet<1.0.0,>=0.20.0 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from terndata.ecoplots) (0.20.0)
Requirement already satisfied: ipywidgets<9.0.0,>=8.1.7 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from terndata.ecoplots) (8.1.8)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.11.12->terndata.ecoplots) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.11.12->terndata.ecoplots) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.11.12->terndata.ecoplots) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.11.12->terndata.ecoplots) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.11.12->terndata.ecoplots) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.11.12->terndata.ecoplots) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.11.12->terndata.ecoplots) (1.22.0)
Requirement already satisfied: branca>=0.5.0 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from ipyleaflet<1.0.0,>=0.20.0->terndata.ecoplots) (0.8.2)
Requirement already satisfied: jupyter-leaflet<0.21,>=0.20 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from ipyleaflet<1.0.0,>=0.20.0->terndata.ecoplots) (0.20.0)
Requirement already satisfied: traittypes<3,>=0.2.1 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from ipyleaflet<1.0.0,>=0.20.0->terndata.ecoplots) (0.2.3)
Requirement already satisfied: xyzservices>=2021.8.1 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from ipyleaflet<1.0.0,>=0.20.0->terndata.ecoplots) (2025.11.0)
Requirement already satisfied: comm>=0.1.3 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from ipywidgets<9.0.0,>=8.1.7->terndata.ecoplots) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from ipywidgets<9.0.0,>=8.1.7->terndata.ecoplots) (9.7.0)
Requirement already satisfied: traitlets>=4.3.1 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from ipywidgets<9.0.0,>=8.1.7->terndata.ecoplots) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from ipywidgets<9.0.0,>=8.1.7->terndata.ecoplots) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from ipywidgets<9.0.0,>=8.1.7->terndata.ecoplots) (3.0.16)
Requirement already satisfied: idna>=2.0 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from yarl<2.0,>=1.17.0->aiohttp<4.0.0,>=3.11.12->terndata.ecoplots) (3.11)
Requirement already satisfied: jinja2>=3 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from branca>=0.5.0->ipyleaflet<1.0.0,>=0.20.0->terndata.ecoplots) (3.1.6)
Requirement already satisfied: decorator>=4.3.2 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets<9.0.0,>=8.1.7->terndata.ecoplots) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets<9.0.0,>=8.1.7->terndata.ecoplots) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets<9.0.0,>=8.1.7->terndata.ecoplots) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.5 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets<9.0.0,>=8.1.7->terndata.ecoplots) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets<9.0.0,>=8.1.7->terndata.ecoplots) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets<9.0.0,>=8.1.7->terndata.ecoplots) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets<9.0.0,>=8.1.7->terndata.ecoplots) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets<9.0.0,>=8.1.7->terndata.ecoplots) (0.6.3)
Requirement already satisfied: wcwidth in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets<9.0.0,>=8.1.7->terndata.ecoplots) (0.2.14)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from jedi>=0.18.1->ipython>=6.1.0->ipywidgets<9.0.0,>=8.1.7->terndata.ecoplots) (0.8.5)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from jinja2>=3->branca>=0.5.0->ipyleaflet<1.0.0,>=0.20.0->terndata.ecoplots) (3.0.3)
Requirement already satisfied: ptyprocess>=0.5 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets<9.0.0,>=8.1.7->terndata.ecoplots) (0.7.0)
Requirement already satisfied: executing>=1.2.0 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets<9.0.0,>=8.1.7->terndata.ecoplots) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets<9.0.0,>=8.1.7->terndata.ecoplots) (3.0.1)
Requirement already satisfied: pure-eval in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets<9.0.0,>=8.1.7->terndata.ecoplots) (0.2.3)
Requirement already satisfied: pyogrio>=0.7.2 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from geopandas->terndata.ecoplots) (0.11.1)
Requirement already satisfied: packaging in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from geopandas->terndata.ecoplots) (25.0)
Requirement already satisfied: pyproj>=3.5.0 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from geopandas->terndata.ecoplots) (3.7.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from pandas->terndata.ecoplots) (2025.2)
Requirement already satisfied: certifi in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from pyogrio>=0.7.2->geopandas->terndata.ecoplots) (2025.11.12)
Requirement already satisfied: six>=1.5 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from python-dateutil->terndata.ecoplots) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from requests->terndata.ecoplots) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/uqjsanc2/projects/terndata.ecoplots/.venv/lib/python3.13/site-packages (from requests->terndata.ecoplots) (2.5.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
from terndata.ecoplots import EcoPlots
ecoplots = EcoPlots()

# Display the client information
print(ecoplots)

╔══════════════════════════════════════════════════════════════════════════════╗
║ EcoPlots                                                                     ║
║ Version: 0.0.4-beta                                                          ║
╠══════════════════════════════════════════════════════════════════════════════╣
║ No filters applied                                                           ║
╚══════════════════════════════════════════════════════════════════════════════╝

In [3]:
ecoplots.select(feature_type="plant occurrence")
ecoplots.get_observed_properties()

,key,uri
0,scientific name,http://linked.data.gov.au/def/tern-cv/56195246...
1,taxon,http://linked.data.gov.au/def/tern-cv/70646576...
2,growth form,http://linked.data.gov.au/def/tern-cv/f81aa91e...
3,in-canopy sky,http://linked.data.gov.au/def/tern-cv/9b2ab960...
4,dead plant,http://linked.data.gov.au/def/tern-cv/cd11241d...
5,plant height,http://linked.data.gov.au/def/tern-cv/09296da0...
6,IUCN conservation status,http://linked.data.gov.au/def/tern-cv/6f59a7ac...
7,plant count,http://linked.data.gov.au/def/tern-cv/bf8dffaf...
8,plant presence,http://linked.data.gov.au/def/tern-cv/c1364f2c...
9,growth stage,http://linked.data.gov.au/def/tern-cv/abb0ee19...
10,EPBC act conservation status,http://linked.data.gov.au/def/tern-cv/fd98815c...

In [52]:

# Select animal occurrence data for the observed property "taxon"
ecoplots.select(feature_type="plant occurrence").select(observed_property=["scientific name", "plant height", "growth form"])
# List available data sources
ecoplots.get_datasources()

                           key                                         uri
0  TERN Ecosystem Surveillance  http://linked.data.gov.au/dataset/ausplots

In [53]:
# Summarise the data before downloading it into a DataFrame
ecoplots.summary()

              metric  count
0       observations   4773
1            dataset      1
2       feature_type      1
3  observed_property      3
4               site      1
5         site_visit      1

In [54]:
ecoplots.select(site_id="NSTSYB0001")

EcoPlots(filterset={'feature_type': ['plant occurrence'], 'observed_property': ['scientific name', 'plant height', 'growth form'], 'site_id': ['NSTSYB0001']}, query_filters={'feature_type': ['http://linked.data.gov.au/def/tern-cv/b311c0d3-4a1a-4932-a39c-f5cdc1afa611'], 'observed_property': ['http://linked.data.gov.au/def/tern-cv/56195246-ec5d-4050-a1c6-af786fbec715', 'http://linked.data.gov.au/def/tern-cv/09296da0-c645-4165-950c-780c21b3c140', 'http://linked.data.gov.au/def/tern-cv/f81aa91e-5f57-4e49-bc6e-4d821d1f9de2'], 'site_id': ['http://linked.data.gov.au/dataset/ausplots/site-nstsyb0001']})

In [7]:
# Summarise the data before downloading it into a DataFrame
ecoplots.summary()

              metric  count
0       observations   4773
1            dataset      1
2       feature_type      1
3  observed_property      3
4               site      1
5         site_visit      1

In [8]:
# Download the data into a DataFrame. By default, this will return a pandas DataFrame.
# The total ammount of data downloaded will be 244k rows. This may take a few moments.
df_plant = ecoplots.get_data()

In [9]:
# Display the first few rows of the DataFrame
df_plant.head()

,datasetTitle,siteName,transectName,latitude_Degree,longitude_Degree,siteVisitName,siteVisitStartDate,siteVisitEndDate,featureType,featureId,...,scientificName.1,scientificNameResultTime,scientificNameMethod,growthForm,growthFormResultTime,growthFormMethod,plantHeight_metre,plantHeightResultTime,plantHeightMethod,geometry
0,TERN Ecosystem Surveillance,NSTSYB0001,NSTSYB0001-transect-S5-N5,-33.67334,151.135,20151111,2015-11-11T12:11:06,2015-11-11T12:11:06,plant occurrence,http://linked.data.gov.au/dataset/ausplots/sit...,...,Corymbia gummifera,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/1d39...,Tree/Palm,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,6.0,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,POINT (151.135 -33.67334)
1,TERN Ecosystem Surveillance,NSTSYB0001,NSTSYB0001-transect-S5-N5,-33.67334,151.135,20151111,2015-11-11T12:11:06,2015-11-11T12:11:06,plant occurrence,http://linked.data.gov.au/dataset/ausplots/sit...,...,Hemigenia purpurea,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/1d39...,Forb,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,0.2,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,POINT (151.135 -33.67334)
2,TERN Ecosystem Surveillance,NSTSYB0001,NSTSYB0001-transect-S5-N5,-33.67334,151.135,20151111,2015-11-11T12:11:06,2015-11-11T12:11:06,plant occurrence,http://linked.data.gov.au/dataset/ausplots/sit...,...,Corymbia gummifera,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/1d39...,Tree/Palm,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,6.0,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,POINT (151.135 -33.67334)
3,TERN Ecosystem Surveillance,NSTSYB0001,NSTSYB0001-transect-S5-N5,-33.67334,151.135,20151111,2015-11-11T12:11:06,2015-11-11T12:11:06,plant occurrence,http://linked.data.gov.au/dataset/ausplots/sit...,...,Corymbia gummifera,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/1d39...,Tree/Palm,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,5.0,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,POINT (151.135 -33.67334)
4,TERN Ecosystem Surveillance,NSTSYB0001,NSTSYB0001-transect-S5-N5,-33.67334,151.135,20151111,2015-11-11T12:11:06,2015-11-11T12:11:06,plant occurrence,http://linked.data.gov.au/dataset/ausplots/sit...,...,Eucalyptus sparsifolia,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/1d39...,Tree/Palm,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,N/A,N/A,N/A,POINT (151.135 -33.67334)

In [55]:
# Count occurrences of each scientific name, sorted in descending order (most frequent first)
df_plant.groupby(by=['growthForm','scientificName']).size().sort_values(ascending=False)

growthForm     scientificName
Tree/Palm      Eucalyptus sparsifolia                        185
               Eucalyptus haemastoma                         154
               Corymbia gummifera                            150
Forb           Hemigenia purpurea                             89
Shrub          Banksia ericifolia                             82
               Phyllota grandiflora                           65
               Xanthorrhoea                                   65
               Leucopogon microphyllus var. pilibundus        64
Forb           Actinotus minor                                62
Shrub          Pultenaea tuberculata                          53
               Leptospermum trinervium                        48
               Calytrix tetragona                             47
               Grevillea sericea                              45
Tree/Palm      Banksia serrata                                45
Sedge          Schoenus imberbis                              41
Shrub          Lambertia formosa                              37
               Dillwynia retorta                              31
               Gompholobium grandiflorum                      30
               Woollsia pungens                               30
               Banksia serrata                                25
               Petrophile pulchella                           25
               Grevillea buxifolia subsp. buxifolia           23
               Corymbia gummifera                             22
Sedge          Indeterminate                                  21
Shrub          Epacris microphylla                            20
Sedge          Cyathochaeta                                   16
               Caustis recurvata                              15
Shrub          Hibbertia bracteata                            12
               Platysace linearifolia                         11
               Persoonia pinifolia                            10
               Eucalyptus haemastoma                           9
Vine           Cassytha pubescens                              8
Shrub          Hakea laevipes                                  7
               Eucalyptus sparsifolia                          6
Tussock grass  Anisopogon avenaceus                            6
Forb           Lomandra glauca                                 6
Shrub          Banksia spinulosa                               6
               Allocasuarina littoralis                        6
               Acacia myrtifolia                               5
               Bossiaea ensata                                 5
               Isopogon anemonifolius                          4
Sedge          Leptocarpus tenax                               4
Shrub          Hakea propinqua                                 3
Tree/Palm      Banksia ericifolia                              3
Sedge          Lepyrodia cryptica                              3
Fern           Gleichenia dicarpa                              3
Shrub          Hakea sericea                                   3
               Banksia oblongifolia                            3
               Olax stricta                                    3
Shrub Mallee   Angophora hispida                               2
Forb           Pultenaea linophylla                            2
               Conospermum longifolium subsp. longifolium      2
               Annual Forb                                     2
Shrub          Acacia suaveolens                               2
               Persoonia levis                                 1
               Dead Tree/Shrub                                 1
dtype: int64

In [42]:
df_plant.dtypes

datasetTitle                  object
siteName                      object
transectName                  object
latitude_Degree              float64
longitude_Degree             float64
siteVisitName                  int64
siteVisitStartDate            object
siteVisitEndDate              object
featureType                   object
featureId                     object
scientificName                object
scientificName.1              object
scientificNameResultTime      object
scientificNameMethod          object
growthForm                    object
growthFormResultTime          object
growthFormMethod              object
plantHeight_metre             object
plantHeightResultTime         object
plantHeightMethod             object
geometry                    geometry
dtype: object

In [43]:
# transform plantHeight_metre to numeric, coerce errors to NaN
import pandas as pd
df_plant['plantHeight_metre'] = pd.to_numeric(df_plant['plantHeight_metre'], errors='coerce')
df_plant['plantHeight_metre'].dtype

dtype('float64')

In [45]:
# Show only two columns: scientificName and plantHeight_metre, and filter the scientificName with max height
df_plant[['scientificName', 'plantHeight_metre']].loc[df_plant.groupby('scientificName')['plantHeight_metre'].idxmax()]

                                  scientificName  plantHeight_metre
625                            Acacia myrtifolia                0.7
977                            Acacia suaveolens                1.5
1273                             Actinotus minor                0.7
1548                    Allocasuarina littoralis                1.2
835                            Angophora hispida                1.3
32                          Anisopogon avenaceus                0.2
801                                  Annual Forb                0.1
494                           Banksia ericifolia                5.0
204                         Banksia oblongifolia                1.5
949                              Banksia serrata                7.0
188                            Banksia spinulosa                2.0
875                              Bossiaea ensata                0.8
677                           Calytrix tetragona                1.3
539                           Cassytha pubescens                0.9
521                            Caustis recurvata                0.9
317   Conospermum longifolium subsp. longifolium                0.7
1487                          Corymbia gummifera               11.0
1447                                Cyathochaeta                0.3
743                              Dead Tree/Shrub                1.1
664                            Dillwynia retorta                1.1
811                          Epacris microphylla                1.0
130                        Eucalyptus haemastoma                9.0
275                       Eucalyptus sparsifolia               10.0
543                           Gleichenia dicarpa                0.5
228                    Gompholobium grandiflorum                1.2
53          Grevillea buxifolia subsp. buxifolia                1.5
1023                           Grevillea sericea                2.2
762                               Hakea laevipes                2.3
112                              Hakea propinqua                2.0
833                                Hakea sericea                1.5
384                           Hemigenia purpurea                1.0
975                          Hibbertia bracteata                0.9
867                                Indeterminate                0.7
1356                      Isopogon anemonifolius                0.8
311                            Lambertia formosa                2.0
205                            Leptocarpus tenax                0.4
470                      Leptospermum trinervium                2.8
1265                          Lepyrodia cryptica                0.3
687      Leucopogon microphyllus var. pilibundus                0.8
428                              Lomandra glauca                0.1
1278                                Olax stricta                2.0
129                              Persoonia levis                0.2
522                          Persoonia pinifolia                1.7
971                         Petrophile pulchella                2.8
1077                        Phyllota grandiflora                1.5
497                       Platysace linearifolia                1.0
1257                        Pultenaea linophylla                0.7
1526                       Pultenaea tuberculata                1.8
742                            Schoenus imberbis                0.4
1241                            Woollsia pungens                1.1
1310                                Xanthorrhoea                1.0

In [46]:
# Group by growthForm and scientificName and calculate the average plant height for each growth form
df_plant.groupby(['growthForm', 'scientificName'])['plantHeight_metre'].mean().reset_index()

,growthForm,scientificName,plantHeight_metre
0,Fern,Gleichenia dicarpa,0.433333
1,Forb,Actinotus minor,0.238548
2,Forb,Annual Forb,0.055000
3,Forb,Conospermum longifolium subsp. longifolium,0.700000
4,Forb,Hemigenia purpurea,0.400562
5,Forb,Lomandra glauca,0.066667
6,Forb,Pultenaea linophylla,0.650000
7,Sedge,Caustis recurvata,0.486667
8,Sedge,Cyathochaeta,0.113750
9,Sedge,Indeterminate,0.260000
10,Sedge,Leptocarpus tenax,0.200000
11,Sedge,Lepyrodia cryptica,0.166667
12,Sedge,Schoenus imberbis,0.090488
13,Shrub,Acacia myrtifolia,0.440000
14,Shrub,Acacia suaveolens,1.050000
15,Shrub,Allocasuarina littoralis,0.808333
16,Shrub,Banksia ericifolia,1.258537
17,Shrub,Banksia oblongifolia,0.966667
18,Shrub,Banksia serrata,1.462800
19,Shrub,Banksia spinulosa,1.450000
20,Shrub,Bossiaea ensata,0.542000
21,Shrub,Calytrix tetragona,0.629787
22,Shrub,Corymbia gummifera,2.476190
23,Shrub,Dead Tree/Shrub,1.100000
24,Shrub,Dillwynia retorta,0.676452
25,Shrub,Epacris microphylla,0.395000
26,Shrub,Eucalyptus haemastoma,1.822222
27,Shrub,Eucalyptus sparsifolia,1.238333
28,Shrub,Gompholobium grandiflorum,0.665000
29,Shrub,Grevillea buxifolia subsp. buxifolia,0.982609
30,Shrub,Grevillea sericea,1.123333
31,Shrub,Hakea laevipes,1.642857
32,Shrub,Hakea propinqua,1.633333
33,Shrub,Hakea sericea,1.433333
34,Shrub,Hibbertia bracteata,0.420833
35,Shrub,Isopogon anemonifolius,0.425000
36,Shrub,Lambertia formosa,0.693243
37,Shrub,Leptospermum trinervium,0.629167
38,Shrub,Leucopogon microphyllus var. pilibundus,0.333750
39,Shrub,Olax stricta,1.500000
40,Shrub,Persoonia levis,0.200000
41,Shrub,Persoonia pinifolia,1.130000
42,Shrub,Petrophile pulchella,0.916667
43,Shrub,Phyllota grandiflora,0.652308
44,Shrub,Platysace linearifolia,0.554545
45,Shrub,Pultenaea tuberculata,0.720755
46,Shrub,Woollsia pungens,0.415000
47,Shrub,Xanthorrhoea,0.365385
48,Shrub Mallee,Angophora hispida,1.200000
49,Tree/Palm,Banksia ericifolia,4.333333
50,Tree/Palm,Banksia serrata,3.680000
51,Tree/Palm,Corymbia gummifera,6.314400
52,Tree/Palm,Eucalyptus haemastoma,5.072072
53,Tree/Palm,Eucalyptus sparsifolia,6.918792
54,Tussock grass,Anisopogon avenaceus,0.101667
55,Vine,Cassytha pubescens,0.481250

In [50]:
# Find the unique tallest plant from the dataframe
df_plant.loc[df_plant['plantHeight_metre'].idxmax()]

datasetTitle                                      TERN Ecosystem Surveillance
siteName                                                           NSTSYB0001
transectName                                        NSTSYB0001-transect-W1-E1
latitude_Degree                                                     -33.67334
longitude_Degree                                                      151.135
siteVisitName                                                        20151111
siteVisitStartDate                                        2015-11-11T12:11:06
siteVisitEndDate                                          2015-11-11T12:11:06
featureType                                                  plant occurrence
featureId                   http://linked.data.gov.au/dataset/ausplots/sit...
scientificName                                             Corymbia gummifera
scientificName.1                                           Corymbia gummifera
scientificNameResultTime                                  2015-11-11T00:00:00
scientificNameMethod        http://linked.data.gov.au/def/ausplots-cv/1d39...
growthForm                                                          Tree/Palm
growthFormResultTime                                      2015-11-11T00:00:00
growthFormMethod            http://linked.data.gov.au/def/ausplots-cv/c5a3...
plantHeight_metre                                                        11.0
plantHeightResultTime                                     2015-11-11T00:00:00
plantHeightMethod           http://linked.data.gov.au/def/ausplots-cv/c5a3...
geometry                                            POINT (151.135 -33.67334)
Name: 1487, dtype: object

In [47]:
# Find the tallest plant in each growth form
df_plant.loc[df_plant.groupby('growthForm')['plantHeight_metre'].idxmax()]

,datasetTitle,siteName,transectName,latitude_Degree,longitude_Degree,siteVisitName,siteVisitStartDate,siteVisitEndDate,featureType,featureId,...,scientificName.1,scientificNameResultTime,scientificNameMethod,growthForm,growthFormResultTime,growthFormMethod,plantHeight_metre,plantHeightResultTime,plantHeightMethod,geometry
543,TERN Ecosystem Surveillance,NSTSYB0001,NSTSYB0001-transect-S4-N4,-33.67334,151.135,20151111,2015-11-11T12:11:06,2015-11-11T12:11:06,plant occurrence,http://linked.data.gov.au/dataset/ausplots/sit...,...,Gleichenia dicarpa,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/1d39...,Fern,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,0.5,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,POINT (151.135 -33.67334)
384,TERN Ecosystem Surveillance,NSTSYB0001,NSTSYB0001-transect-N2-S2,-33.67334,151.135,20151111,2015-11-11T12:11:06,2015-11-11T12:11:06,plant occurrence,http://linked.data.gov.au/dataset/ausplots/sit...,...,Hemigenia purpurea,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/1d39...,Forb,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,1.0,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,POINT (151.135 -33.67334)
521,TERN Ecosystem Surveillance,NSTSYB0001,NSTSYB0001-transect-S4-N4,-33.67334,151.135,20151111,2015-11-11T12:11:06,2015-11-11T12:11:06,plant occurrence,http://linked.data.gov.au/dataset/ausplots/sit...,...,Caustis recurvata,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/1d39...,Sedge,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,0.9,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,POINT (151.135 -33.67334)
488,TERN Ecosystem Surveillance,NSTSYB0001,NSTSYB0001-transect-S4-N4,-33.67334,151.135,20151111,2015-11-11T12:11:06,2015-11-11T12:11:06,plant occurrence,http://linked.data.gov.au/dataset/ausplots/sit...,...,Banksia ericifolia,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/1d39...,Shrub,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,4.0,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,POINT (151.135 -33.67334)
835,TERN Ecosystem Surveillance,NSTSYB0001,NSTSYB0001-transect-W5-E5,-33.67334,151.135,20151111,2015-11-11T12:11:06,2015-11-11T12:11:06,plant occurrence,http://linked.data.gov.au/dataset/ausplots/sit...,...,Angophora hispida,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/1d39...,Shrub Mallee,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,1.3,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,POINT (151.135 -33.67334)
1487,TERN Ecosystem Surveillance,NSTSYB0001,NSTSYB0001-transect-W1-E1,-33.67334,151.135,20151111,2015-11-11T12:11:06,2015-11-11T12:11:06,plant occurrence,http://linked.data.gov.au/dataset/ausplots/sit...,...,Corymbia gummifera,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/1d39...,Tree/Palm,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,11.0,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,POINT (151.135 -33.67334)
32,TERN Ecosystem Surveillance,NSTSYB0001,NSTSYB0001-transect-S5-N5,-33.67334,151.135,20151111,2015-11-11T12:11:06,2015-11-11T12:11:06,plant occurrence,http://linked.data.gov.au/dataset/ausplots/sit...,...,Anisopogon avenaceus,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/1d39...,Tussock grass,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,0.2,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,POINT (151.135 -33.67334)
539,TERN Ecosystem Surveillance,NSTSYB0001,NSTSYB0001-transect-S4-N4,-33.67334,151.135,20151111,2015-11-11T12:11:06,2015-11-11T12:11:06,plant occurrence,http://linked.data.gov.au/dataset/ausplots/sit...,...,Cassytha pubescens,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/1d39...,Vine,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,0.9,2015-11-11T00:00:00,http://linked.data.gov.au/def/ausplots-cv/c5a3...,POINT (151.135 -33.67334)